version: '3'
services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - ./data/pgdata:/pgdata
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=ifsc
      - POSTGRES_PASSWORD=ifsc_postgres
      - PGDATA=/pgdata
  redis:
    image: redis:4.0.6-alpine
    ports:
      - "6379:6379"
  app:
    build:
      context: .
      args:
        app_env: ${APP_ENV}
    image: ifsc:latest
    ports:
      - "3000:3000"
    links:
      - db