version: '3'
services:
  db:
    image: postgres:10.1-alpine
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - PGDATA=/pgdata
  app:
    build: .
    ports:
      - "5000:5000"
    links:
      - db
  